// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export const components = {
  "Foo": {
    "type": "COMPONENT",
    "id": "Foo",
    "title": "Foo",
    "propsConfig": {
      "type": "object",
      "required": [
        "title"
      ],
      "className": "__type",
      "properties": {
        "title": {
          "type": "string",
          "description": "标题",
          "tags": {
            "description": "标题"
          }
        },
        "order": {
          "type": "number",
          "description": "顺序",
          "tags": {
            "description": "顺序"
          }
        }
      }
    }
  }
};
