// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import * as tab0 from '/Users/yuantu/Desktop/github/dumi-exapmles/normal/src/Foo/index.$tab-api.md';
import * as tab1 from '/Users/yuantu/Desktop/github/dumi-exapmles/normal/a.tsx';

export const tabs = {
  'src/Foo/index.$tab-api': { key: 'api', components: tab0 },
  'plugin-tab-test': { key: 'test', components: tab1 },
}
