// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
export { default } from '/Users/yuantu/Desktop/github/dumi-exapmles/normal/node_modules/.pnpm/dumi@2.0.13_qtbnez4q7bzoc4eqybg3efzzxe/node_modules/dumi/theme-default/slots/Content/index.js';
