// @ts-nocheck
// This file is generated by Umi automatically
// DO NOT CHANGE IT MANUALLY!
import React from 'react';

export async function getRoutes() {
  return {
    routes: {"404":{"id":"404","path":"*","parentId":"DocLayout"},"dumi-context-layout":{"id":"dumi-context-layout","path":"/","isLayout":true},"DocLayout":{"id":"DocLayout","path":"/","parentId":"dumi-context-layout","isLayout":true},"nothing":{"path":"nothing","id":"nothing","parentId":"DocLayout"},"docs/hello/index":{"path":"hello","id":"docs/hello/index","parentId":"DocLayout"},"docs/index":{"path":"","id":"docs/index","parentId":"DocLayout"},"components/Foo/index.en-US":{"id":"components/Foo/index.en-US","path":"en-US/components/foo","parentId":"DocLayout"},"components/Foo/index":{"id":"components/Foo/index","path":"components/foo","parentId":"DocLayout"},"demo-render":{"id":"demo-render","path":"~demos/:id","parentId":"dumi-context-layout"}},
    routeComponents: {
'404': React.lazy(() => import(/* webpackChunkName: "nm__.pnpm__dumi_2.0.13_qtbnez4q7bzoc4eqybg3efzzxe__node_modules__dumi__dist__client__pages__404" */'/Users/yuantu/Desktop/github/dumi-exapmles/normal/node_modules/.pnpm/dumi@2.0.13_qtbnez4q7bzoc4eqybg3efzzxe/node_modules/dumi/dist/client/pages/404.js')),
'dumi-context-layout': React.lazy(() => import(/* webpackChunkName: "dumi__tmp__dumi__theme__ContextWrapper" */'/Users/yuantu/Desktop/github/dumi-exapmles/normal/.dumi/tmp/dumi/theme/ContextWrapper.tsx')),
'DocLayout': React.lazy(() => import(/* webpackChunkName: "nm__.pnpm__dumi_2.0.13_qtbnez4q7bzoc4eqybg3efzzxe__node_modules__dumi__theme-default__layouts__DocLayout__index" */'/Users/yuantu/Desktop/github/dumi-exapmles/normal/node_modules/.pnpm/dumi@2.0.13_qtbnez4q7bzoc4eqybg3efzzxe/node_modules/dumi/theme-default/layouts/DocLayout/index.js')),
'nothing': React.lazy(() => import(/* webpackChunkName: "dumi__pages__nothing" */'/Users/yuantu/Desktop/github/dumi-exapmles/normal/.dumi/pages/nothing.tsx')),
'docs/hello/index': React.lazy(() => import(/* webpackChunkName: "docs__hello__index.md" */'/Users/yuantu/Desktop/github/dumi-exapmles/normal/docs/hello/index.md')),
'docs/index': React.lazy(() => import(/* webpackChunkName: "docs__index.md" */'/Users/yuantu/Desktop/github/dumi-exapmles/normal/docs/index.md')),
'components/Foo/index.en-US': React.lazy(() => import(/* webpackChunkName: "Foo__index.en-US.md" */'/Users/yuantu/Desktop/github/dumi-exapmles/normal/src/Foo/index.en-US.md')),
'components/Foo/index': React.lazy(() => import(/* webpackChunkName: "Foo__index.md" */'/Users/yuantu/Desktop/github/dumi-exapmles/normal/src/Foo/index.md')),
'demo-render': React.lazy(() => import(/* webpackChunkName: "nm__.pnpm__dumi_2.0.13_qtbnez4q7bzoc4eqybg3efzzxe__node_modules__dumi__dist__client__pages__Demo__index" */'/Users/yuantu/Desktop/github/dumi-exapmles/normal/node_modules/.pnpm/dumi@2.0.13_qtbnez4q7bzoc4eqybg3efzzxe/node_modules/dumi/dist/client/pages/Demo/index.js')),
},
  };
}
